---
title: "Meetup 10-2015"
description: "Next meetup announcement with more features and collaboration."
tags: [ "Meetup" ]
date: "2015-10-20T21:31:57+02:00"
---

Main focus this time will be to discuss future directions/projects for ViennaR:  

1. Our goal is to define R-package(s) organized as Github project(s) that can be realised within a timeframe of approx. one year resulting in CRAN release   
- Agree on the main areas (project streams) - not more than 2, max. 3    
- Brainstorm on potential project and/or package ideas 
- Decide on project leads, team members respectively form of collaboration (fork & pull vs. shared repo), type of license (GPL?), etc.       

2. Evaluate interest in active preparation of short analytical topics  (monthly or bi-monthly) to be worked off individually or in groups (alternative: as a hackathon)  
e.g. run a short analysis on some topic based on publicly available data;  present these @ meetup, compare approaches to project solution. 

<!--more-->

Example topics could cover

- Open government data: 
	- Text mine parliamentary votes (by time/topic) (source: https://www.data.gv.at/katalog/dataset/1a3c44a8-7361-4dc7-ac0d-6ec19ddba191)  
	- Graphically display distribution of specific points of interest like voting booths, public toilets, etc. in Vienna based upon https://open.wien.gv.at/site/open-data/) 
- News-related data:
	- Analyze comments for specific topics of derstandard.at
- Price-data
	- e.g. correlate fuel prices in Austria with crude oil prices

We are looking forward to a fruitful/interesting/controversial discussion!
